// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        // Use Web configuration for Windows
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8KzlNAulqWE3wcGFGGZoXnpUOcsngbjk',
    appId: '1:1095515049764:web:272b5f4048c4e6b3286db1',
    messagingSenderId: '1095515049764',
    projectId: 'checkersgame-fa807',
    authDomain: 'checkersgame-fa807.firebaseapp.com',
    databaseURL: 'https://checkersgame-fa807-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'checkersgame-fa807.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAti_ZzCVyk1nVvKxs1Ae-jPCsXi7r-tPY',
    appId: '1:1095515049764:android:674d3f376b052d9a286db1',
    messagingSenderId: '1095515049764',
    projectId: 'checkersgame-fa807',
    databaseURL: 'https://checkersgame-fa807-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'checkersgame-fa807.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'replace-with-your-api-key',
    appId: 'replace-with-your-app-id',
    messagingSenderId: 'replace-with-your-messaging-sender-id',
    projectId: 'replace-with-your-project-id',
    storageBucket: 'checkersgame-fa807.appspot.com',
    iosClientId: 'replace-with-your-ios-client-id',
    iosBundleId: 'com.example.checkersGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'replace-with-your-api-key',
    appId: 'replace-with-your-app-id',
    messagingSenderId: 'replace-with-your-messaging-sender-id',
    projectId: 'replace-with-your-project-id',
    storageBucket: 'checkersgame-fa807.appspot.com',
    iosClientId: 'replace-with-your-ios-client-id',
    iosBundleId: 'com.example.checkersGame',
  );
}